
spring:
  application:
    name: tfl-proxy
  profiles:
    active: dev


main:
  defaultStop: 490009538S

stop-mapping:
  stops:
    490009538N: "MDV Road > Brentford"
    490009538S: "MDV Road > Twickenham"
    490007338JC: "Grainger Road"
    490008512TH: "Isleworth War Memorial"
    TestStop:   "Test Stop Name"

destination-mapping:
  destinations:
    '[Hammersmith, Bus Station]': "Hammersmith"
    '[West Middlesex Hospital]': "Westmid"
    '[Isleworth, West Middlesex Hospital]': "Isleworth, Westmid"
    '[Hounslow, Bell Corner]': "Hns, Bell Corner"
    '[Richmond, Manor Circus]': "Richmond"
    '[Example for Testing]': "Test Destination Name"
---
spring:
  config:
    activate:
      on-profile: dev

main:
  env: DEV
  revertToDefaultValue: 10
  revertToDefaultTimeUnit: SECONDS
  apiKey: DEV_API_KEY

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - "optional:aws-parameterstore:/tfl-proxy/"
aws:
  paramstore:
    prefix: /tfl-proxy
    default-context: tfl-proxy
    profile-separator: _

main:
  env: PROD
  revertToDefaultValue: 10
  revertToDefaultTimeUnit: MINUTES